server:
  port: 9090
  servlet:
    context-path: /proyecto

spring:
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    databae: postgresql

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prueba
    username: postgres
    password: 1234


